---
skip:
  - "./spec/features/frontend/rewards/categories_spec.rb:Categories with a multi-category catalogue viewing categories index category has featured products passing a sort by criteria sorts products by given criteria"
  - "./spec/features/frontend/rewards/categories_spec.rb:Categories with a multi-category catalogue viewing categories index category has featured products orders un-featured products by points value highest to lowest"
  - "./spec/models/registration_question_spec.rb:RegistrationQuestion deleting registration questions with linked answers removes linked answers and answer values"
