---
skip:
  # issue with locale determinator
  - "./spec/features/admin_backend/paper_trail/checking_versions_spec.rb:paper_trail for versioning not a super_admin cannot see the paper_trail link on super_admin layout"

  # Feb 2018
  - "./spec/models/file_processor/users_file_processor_spec.rb:UsersFileProcessor#process_file with user data in another language and programme default locale matches language creates registration answers for each user in csv"

  #  Aug 2018
  - "./spec/features/admin_backend/privacy_policy/editing_privacy_policy_spec.rb:editing a privacy policy admin can switch from disabled to enabled"
  - "./spec/features/admin_backend/privacy_policy/editing_privacy_policy_spec.rb:editing a privacy policy admin can switch from disabled to enabled"

  # Aug 2018 - whole file was skipped, but I know we spent quite some time building these tests and they are important (order button)
  # Consider rewriting as Cypress tests
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories product has physical variants user has enough points for order user can place a valid order for variants"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories product has physical variants user has insufficient points for order user cannot order as the order button is disabled"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories product has physical variants user see the points value for the product as the product_programme points"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories product is a voucher variant is not available user cannot add variant to the order"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories product is a voucher user has insufficient points user cannot order as order button is disabled"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories product is a voucher user has enough points for order total quantaties of variants is 0 user cannot place order when total quantity of order is 0"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories product is a voucher user has enough points for order variant is available user can place order for mulitple vouchers"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories viewing a physical product user sees the quantity field defaulted to 1"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories viewing a physical product user sees the points value for the product as the product_programme points"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories viewing a physical product user has enough points for order product is available user can place a valid order"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories viewing a physical product user has enough points for order product is available viewing a prepaid product allows user to order prepaid product"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories viewing a physical product user has enough points for order product is unavailable user cannot order the product as the order button is disabled"
  - "./spec/features/frontend/orders/product_order_button_spec.rb:Product Order Button catalogue has categories viewing a physical product user has insufficient points for order user cannot order as the order button is disabled"

  # March 2020
  - "./spec/features/frontend/rewards/categories_spec.rb:Categories with a multi-category catalogue viewing categories index category has featured products passing a sort by criteria sorts products by given criteria"
  - "./spec/features/frontend/rewards/categories_spec.rb:Categories with a multi-category catalogue viewing categories index category has featured products orders un-featured products by points value highest to lowest"
  - "./spec/models/registration_question_spec.rb:RegistrationQuestion deleting registration questions with linked answers removes linked answers and answer values"
  - "./spec/models/file_processor/users_file_processor_spec.rb:UsersFileProcessor#process_file with valid value data pre_registration programme with additional_details = true additional_details are false sets consented to true, updates consented_at, & allows User creation"
  - "./spec/features/admin_backend/cms/custom_layout_article_spec.rb:Custom Layout Articles adding widgets"

  # March 2021
  # Suspect this is due to incorrectly-escaped interpolated values being passed to an evaluated JS script
  - "./spec/features/frontend/recognition/campaigns/ethankyou_campaign_spec.rb:Ethankyou when sending an ecard campaign allows points to be added my ecard is submitted for approval"

  # May 2021
  # There's a known race condition here in the JS code that's probably the cause of the flakiness
  - "./spec/features/admin_backend/cms/bg_colour_widget_spec.rb:bg_colour widget giving the dropzone a colour the dropzone should retain the colour selection"
  - "./spec/features/admin_backend/cms/bg_colour_widget_spec.rb:bg_colour widget making the dropzone transparent the dropzone background colour should be 'transparent'"
  - "./spec/features/admin_backend/cms/bg_colour_widget_spec.rb:bg_colour widget the default dropzone background-colour should be #ffffff (white)"
  
  # Jan 2022
  # CKEditor issue?
  - "./spec/features/admin_backend/programmes/performance/promotions_spec.rb:Promotions Editing promotion Display allows admin to change promotion description"

  # July 2022
  - "./spec/features/admin_backend/users/approve_spec.rb:Approve pending users Editing a pending user I can edit the profile of a user pending approval"

  # Jan 2024
  - "./spec/models/budget_spec.rb:Budget#promotion_statement without a manage_budget deducting points from approved claim does not return manage_budget description"
